#!/bin/bash

sudo tmux new -d -s badvpn '
sudo ip tuntap add dev tun0 mode tun user influencingtrot;
sudo ip addr replace 10.0.0.1/24 dev tun0;
badvpn-tun2socks --tundev tun0 --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:8989 --udpgw-remote-server-addr 127.0.0.1:7300;
'
sudo tmux new -s route-43 '
sudo ip route add 103.253.26.215 via 192.168.43.1 metric 5;
sudo ip route add 162.244.81.238 via 192.168.43.1 metric 5;
sudo ip route add 103.253.26.216 via 192.168.43.1 metric 5;
sudo ip route add 217.197.160.162 via 192.168.43.1 metric 5;
sudo ip route add 51.81.80.128 via 192.168.43.1 metric 5;
sudo ip route add 81.90.188.224 via 192.168.43.1 metric 5;
sudo ip route add 8.8.8.8 via 192.168.43.1 metric 5;
'
sudo tmux new -s tun '
sudo ifconfig tun0 10.0.0.1 netmask 255.255.255.0;
sudo route add default gw 10.0.0.2 metric 6;
sudo ifconfig tun0 up;
'
